modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "netmusic_radio_addon"
version = "0.0.1"
displayName = "NetMusic:Radio Addon"
authors = "Keager"
description = '''A radio station search and playback addon for NetMusic. Provides a searchable radio browser with favorites, online/local search, and Shoutcast/Icecast stream support.'''

[[dependencies.netmusic_radio_addon]]
modId = "netmusic"
mandatory = true
versionRange = "[0.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netmusic_radio_addon]]
modId = "forge"
mandatory = true
versionRange = "[47.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netmusic_radio_addon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"